// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CachedTextureResult 是 GetCachedTexture 的返回值。
 */
export interface CachedTextureResult {
    /**
     * "ktx2" | "png"
     */
    "format": string;

    /**
     * base64 编码的纹理数据
     */
    "data": string;

    /**
     * 纹理内容的 SHA256
     */
    "hash": string;
}

/**
 * DownloadTask 下载队列任务
 */
export interface DownloadTask {
    "url": string;
    "saveDir": string;
    "name": string;
    "size": number;
}

/**
 * QueueStatusInfo 队列状态（替代多返回值，Wails 自动映射为 JS object）
 */
export interface QueueStatusInfo {
    "remaining": number;
    "running": boolean;
}
