#!/usr/bin/env node
/**
 * eg_gen.mjs — 生成 scripts/event-graph.mjs
 * 通过此 generator 避免在 bash 中直接写含反引号的文件
 */
import fs from 'fs';

const lines = [];
const L = (s='') => lines.push(s);

L('#!/usr/bin/env node');
L('/**');
L(' * event-graph.mjs — Bus 事件契约守护者。');
L(' * 从 bus.ts 的 BusEvents 接口提取权威事件清单，扫描 frontend/src/ 和 index.html，');
L(' * 报告未声明事件 / 孤儿发射 / 鬼订阅 / 跨行调用。');
L(' * 用法：node scripts/event-graph.mjs [--check] [--json] [--strict]');
L(' */');
L("import fs from 'node:fs';");
L("import path from 'node:path';");
L("import { getRoot, relPosix } from './_lib/scan-files.mjs';");
L('');
L('const ROOT = getRoot();');
L("const SRC_DIR = path.join(ROOT, 'frontend', 'src');");
L("const INDEX_HTML = path.join(ROOT, 'frontend', 'index.html');");
L("const BUS_TS = path.join(SRC_DIR, 'bus.ts');");
L("const OUT = path.join(ROOT, 'docs', 'event-graph.md');");
L('const ARGS = new Set(process.argv.slice(2));');
L("const CHECK = ARGS.has('--check');");
L("const JSON_OUT = ARGS.has('--json');");
L("const STRICT = ARGS.has('--strict');");
L('');
L('function readBusEvents() {');
L("  const text = fs.readFileSync(BUS_TS, 'utf-8');");
L('  const events = new Set();');
L(`  const re = /"([^"]+)"\\s*:/g;`);
L('  let m;');
L('  while ((m = re.exec(text)) !== null) {');
L('    const ev = m[1];');
L(`    const lineStart = text.lastIndexOf('\\n', m.index) + 1;`);
L(`    const line = text.slice(lineStart, text.indexOf('\\n', m.index)).trim();`);
L("    if (line.startsWith('//') || line.startsWith('*') || line.startsWith('-')) continue;");
L('    events.add(ev);');
L('  }');
L('  return events;');
L('}')
L('');
L('function stripNoise(text) {');
L('  return text');
L(`    .replace(/\\/\\*[\\s\\S]*?\\*\\//g, ' ')`);
L(`    .replace(/\\/\\/.*$/gm, ' ');`);
L('}')
L('');
L('function collectSrcFiles() {');
L('  const files = [];');
L('  const walk = (dir) => {');
L('    if (!fs.existsSync(dir)) return;');
L('    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {');
L("      if (ent.name.startsWith('.')) continue;");
L('      const p = path.join(dir, ent.name);');
L('      if (ent.isDirectory()) walk(p);');
L(`      else if (/\\.(ts|js)$/.test(ent.name) && !ent.name.endsWith('.test.ts') && !ent.name.endsWith('.spec.ts')) {`);
L('        files.push(p);');
L('      }');
L('    }');
L('  };');
L('  walk(SRC_DIR);');
L('  return files;');
L('}')
L('');
L('function scanFiles(files, includeHtml) {');
L('  const eventMap = new Map();');
L('  function add(event, method, file, line) {');
L('    if (!eventMap.has(event)) eventMap.set(event, { emit: [], on: [], once: [], off: [] });');
L('    eventMap.get(event)[method].push({ file, line });');
L('  }');
L('  function scanFile(filePath, rel) {');
L("    const text = stripNoise(fs.readFileSync(filePath, 'utf-8'));");
L("    const lines = text.split('\\n');");
L('    for (let i = 0; i < lines.length; i++) {');
L('      const line = lines[i];');
L(`      const lineRe = /(?:^|[^A-Za-z0-9_$])([A-Za-z_$][\\w$]*)\\.(emit|on|once|off)\\s*\\(\\s*['"]([^'"]+)['"]/g;`);
L('      let m;');
L('      while ((m = lineRe.exec(line)) !== null) add(m[3], m[2], rel, i + 1);');
L(`      if (/\\.((?:emit|on|once|off)\\s*\\(\\s*)$/.test(line.trimEnd())) {`);
L('        if (i + 1 < lines.length) {');
L('          const next = lines[i + 1].trimStart();');
L(`          const crossM = next.match(/^(['"])([^'"]+)\\1/);`);
L('          if (crossM) {');
L(`            const parentM = line.match(/([A-Za-z_$][\\w$]*)\\.(emit|on|once|off)$/);`);
L('            if (parentM) add(crossM[2], parentM[2], rel, i + 1);');
L('          }');
L('        }');
L('      }');
L('    }');
L('  }');
L('  for (const f of files) scanFile(f, relPosix(f));');
L('  if (includeHtml && fs.existsSync(INDEX_HTML)) scanFile(INDEX_HTML, relPosix(INDEX_HTML));');
L('  return { eventMap };');
L('}')
L('');
L('function checkContract(eventMap, declaredEvents) {');
L('  const undeclared = [], orphans = [], ghosts = [];');
L('  for (const [ev, d] of eventMap) {');
L('    if (!declaredEvents.has(ev) && !undeclared.includes(ev)) undeclared.push(ev);');
L('    if (d.emit.length > 0 && d.on.length === 0 && d.once.length === 0 && !orphans.includes(ev)) orphans.push(ev);');
L('    if ((d.on.length > 0 || d.once.length > 0) && d.emit.length === 0 && !ghosts.includes(ev)) ghosts.push(ev);');
L('  }');
L('  return { undeclared, orphans, ghosts };');
L('}')
L('');
L('function renderMarkdown(eventMap, anomalies) {');
L('  const out = [];');
L("  out.push('# Bus 事件契约报告');");
L("  out.push('');");
L("  out.push('> **自动生成** — 由 `scripts/event-graph.mjs` 生成。');");
L("  out.push('> 基于 `frontend/src/bus.ts` 的 `BusEvents` 接口校验所有调用方。');");
L("  out.push('');");
L('  if (anomalies.undeclared.length || anomalies.orphans.length || anomalies.ghosts.length) {');
L("    out.push('## \\u26a0\\ufe0f 异常摘要');");
L("    out.push('');");
L('    if (anomalies.undeclared.length) {');
L("      out.push('### 未声明事件（不在 BusEvents 中，可能是 typo 或漏声明）');");
L("      out.push('');");
L('      for (const ev of anomalies.undeclared) { const d = eventMap.get(ev); out.push(`- \\`${ev}\\` — emit×${d.emit.length} on×${d.on.length}`); }');
L("      out.push('');");
L('    }');
L('    if (anomalies.orphans.length) {');
L("      out.push('### 孤儿发射（emit 了但无 on/once 订阅方）');");
L("      out.push('');");
L('      for (const ev of anomalies.orphans) { const d = eventMap.get(ev); out.push(`- \\`${ev}\\` — emit×${d.emit.length}`); }');
L("      out.push('');");
L('    }');
L('    if (anomalies.ghosts.length) {');
L("      out.push('### 鬼订阅（有 on/once 但从未被 emit）');");
L("      out.push('');");
L('      for (const ev of anomalies.ghosts) { const d = eventMap.get(ev); out.push(`- \\`${ev}\\` — on×${d.on.length}`); }');
L("      out.push('');");
L('    }');
L('  } else {');
L("    out.push('## \\u2705 无异常');");
L("    out.push('');");
L('    out.push("所有调用均在 BusEvents 契约内，无孤儿发射 / 鬼订阅 / 未声明事件。");');
L("    out.push('');");
L('  }');
L('  const events = [...eventMap.keys()].sort();');
L("  out.push('## 事件总览');");
L("  out.push('');");
L("  out.push('| 事件 | 发射方 | 订阅方 | 一次性订阅 | 退订方 | 状态 |');");
L("  out.push('|------|--------|--------|-----------|--------|------|');");
L('  for (const ev of events) {');
L('    const d = eventMap.get(ev);');
L('    let status = "\\u2705";');
L('    if (anomalies.undeclared.includes(ev)) status = "\\u26a0\\ufe0f 未声明";');
L('    else if (d.emit.length > 0 && d.on.length === 0 && d.once.length === 0) status = "\\ud83d\\udd07 孤儿发射";');
L('    else if (d.emit.length === 0 && (d.on.length > 0 || d.once.length > 0)) status = "\\ud83d\\udc7b 鬼订阅";');
L('    out.push(`| \\`${ev}\\` | ${d.emit.length} | ${d.on.length} | ${d.once.length} | ${d.off.length} | ${status} |`);');
L('  }');
L("  out.push('');");
L("  out.push('## 调用详情');");
L("  out.push('');");
L('  for (const ev of events) {');
L('    const d = eventMap.get(ev);');
L('    out.push(`### \\`${ev}\\``);');
L("    out.push('');");
L('    if (d.emit.length) { out.push("**发射方：**"); out.push("| 文件 | 行 |"); out.push("|------|----|"); for (const e of d.emit) out.push(`| \\`${e.file}\\` | ${e.line} |`); out.push(""); }');
L('    if (d.on.length) { out.push("**订阅方（on）：**"); out.push("| 文件 | 行 |"); out.push("|------|----|"); for (const e of d.on) out.push(`| \\`${e.file}\\` | ${e.line} |`); out.push(""); }');
L('    if (d.once.length) { out.push("**一次性订阅（once）：**"); out.push("| 文件 | 行 |"); out.push("|------|----|"); for (const e of d.once) out.push(`| \\`${e.file}\\` | ${e.line} |`); out.push(""); }');
L('    if (d.off.length) { out.push("**退订方：**"); out.push("| 文件 | 行 |"); out.push("|------|----|"); for (const e of d.off) out.push(`| \\`${e.file}\\` | ${e.line} |`); out.push(""); }');
L('  }');
L("  return out.join('\\n');");
L('}')
L('');
L('function renderJSON(eventMap, anomalies) {');
L('  const events = [...eventMap.keys()].sort();');
L('  const data = {};');
L('  for (const ev of events) {');
L('    const d = eventMap.get(ev);');
L('    data[ev] = {');
L('      emit: d.emit.map((e) => `${e.file}:${e.line}`),');
L('      on: d.on.map((e) => `${e.file}:${e.line}`),');
L('      once: d.once.map((e) => `${e.file}:${e.line}`),');
L('      off: d.off.map((e) => `${e.file}:${e.line}`),');
L('    };');
L('  }');
L('  return JSON.stringify({');
L('    _summary: { events: events.length, undeclared: anomalies.undeclared, orphans: anomalies.orphans, ghosts: anomalies.ghosts },');
L('    events: data,');
L('  }, null, 2);');
L('}')
L('');
L('function printAnomalyReport(anomalies) {');
L('  if (!anomalies.undeclared.length && !anomalies.orphans.length && !anomalies.ghosts.length) {');
L('    console.warn("[event-graph] \\u2705 无异常");');
L('    return;');
L('  }');
L("  console.warn('');");
L("  console.warn('\\u2550'.repeat(37));");
L("  console.warn(' Bus 事件契约检查报告');");
L("  console.warn('\\u2550'.repeat(37));");
L('  if (anomalies.undeclared.length) {');
L("    console.warn('\\u26a0\\ufe0f  未声明事件（需审查是否 typo 或漏声明）：');");
L('    for (const ev of anomalies.undeclared) console.warn(`   ${ev}`);');
L('  }');
L('  if (anomalies.orphans.length) {');
L("    console.warn('\\ud83d\\udd07 孤儿发射（emit 无 on/once）：');");
L('    for (const ev of anomalies.orphans) console.warn(`   ${ev}`);');
L('  }');
L('  if (anomalies.ghosts.length) {');
L("    console.warn('\\ud83d\\udc7b 鬼订阅（on/once 无 emit）：');");
L('    for (const ev of anomalies.ghosts) console.warn(`   ${ev}`);');
L('  }');
L("  console.warn('\\u2550'.repeat(37));");
L('  console.warn("说明：未声明事件是硬错误（建议修复）；孤儿/鬼订阅可能是有意设计，仅作记录。--strict 会把未声明事件升级为 exit(1)。");');
L('}')
L('');
L('function main() {');
L("  if (!fs.existsSync(BUS_TS)) { console.error('\\u274c frontend/src/bus.ts 不存在'); process.exit(1); }");
L("  if (!fs.existsSync(SRC_DIR)) { console.error('\\u274c frontend/src 不存在'); process.exit(1); }");
L('  const declaredEvents = readBusEvents();');
L("  console.warn(\`[event-graph] BusEvents 权威清单：\${declaredEvents.size} 个事件\`);");
L('  const files = collectSrcFiles();');
L("  console.warn(\`[event-graph] 扫描源码文件：\${files.length} 个\`);");
L('  const { eventMap } = scanFiles(files, true);');
L("  console.warn(\`[event-graph] 扫描到事件：\${eventMap.size} 个\`);");
L('  const anomalies = checkContract(eventMap, declaredEvents);');
L("  console.warn(\`[event-graph] 异常：未声明 \${anomalies.undeclared.length}，孤儿发射 \${anomalies.orphans.length}，鬼订阅 \${anomalies.ghosts.length}\`);");
L('  if (STRICT && anomalies.undeclared.length > 0) {');
L("    console.error('');");
L("    console.error('\\u274c --strict 下发现未声明事件，阻断退出：');");
L('    for (const ev of anomalies.undeclared) console.error(`  ${ev}`);');
L('    process.exit(1);');
L('  }');
L("  if (JSON_OUT) { console.log(renderJSON(eventMap, anomalies)); return; }");
L('  if (CHECK) {');
L("    const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf-8') : '';");
L('    const md = renderMarkdown(eventMap, anomalies);');
L('    if (existing !== md) {');
L("      console.error('\\u274c docs/event-graph.md 过期，运行 \`node scripts/event-graph.mjs\` 刷新。');");
L('      printAnomalyReport(anomalies);');
L('      process.exit(1);');
L('    }');
L("    console.log('\\u2705 docs/event-graph.md 最新。');");
L('    printAnomalyReport(anomalies);');
L('    return;');
L('  }');
L("  fs.writeFileSync(OUT, renderMarkdown(eventMap, anomalies), 'utf-8');");
L("  console.log(\`\\ud83d\\udce6 已写入 \${OUT}（\${eventMap.size} 个事件）\`);");
L('  printAnomalyReport(anomalies);');
L('}')
L('main();');

fs.writeFileSync('C:/Users/zhujieling11/ysm-model-manager/scripts/event-graph.mjs', lines.join('\n'), 'utf-8');
console.log(`generated ${lines.length} lines`);
